version: '3.9'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
  bot:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./src
      - ./prod
      - ./node_modules
    ports:
      - "8080:8080"